export const GET_PRODUCTS_BEGIN = "GET_PRODUCTS_BEGIN";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL";

export const ADD_CART = "ADD_CART";
export const MODIFY_CART = "MODIFY_CART";
export const REMOVE_CART = "REMOVE_CART";
export const PRICE_CART = "PRICE_CART";
export const PRICE_REMOVE_CART = "PRICE_REMOVE_CART";
export const SET_LOCAL_CART = "SET_LOCAL_CART";
export const REMOVE_LOCAL_CART = "REMOVE_LOCAL_CART";

export const ORDER_BY_CATEGORY = "ORDER_BY_CATEGORY";
export const ORDER_BY = "ORDER_BY";

export const GET_PRODUCT_BEGIN = "GET_PRODUCT";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_FAIL = "GET_PRODUCT_FAIL";

export const DELETE_PRODUCT = "DELETE_PRODUCT";

export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_TALLES = "GET_TALLES";

export const GET_PRODUCTS_BEGIN_SEARCH = "GET_PRODUCTS_BEGIN_SEARCH";
export const GET_PRODUCTS_SUCCESS_SEARCH = "GET_PRODUCTS_SUCCESS_SEARCH";
export const GET_PRODUCTS_FAIL_SEARCH = "GET_PRODUCTS_FAIL_SEARCH";

export const LOGIN_BEGIN = "LOGIN_BEGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const GET_USUARIO_BEGIN = "GET_USUARIO_BEGIN";
export const GET_USUARIOS_SUCCESS = "GET_USUARIOS_SUCCESS";
export const GET_USUARIOS_FAIL = "GET_USUARIOS_FAIL";

export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const LOGOUT = "LOGOUT";

export const CHECKOUT = "CHECKOUT";
export const GUARDAR_DATOS_COMPRADOR = "GUARDAR_DATOS_COMPRADOR";
export const CREAR_PEDIDO = "CREAR_PEDIDO";

export const GET_PEDIDOS = "GET_PEDIDOS";
export const GET_USUARIOS = "GET_USUARIOS";
export const PUT_USUARIOS = "PUT_USUARIOS";

export const GET_FACTURA = "GET_FACTURA";
export const APROBAR_PEDIDO = "APROBAR_PEDIDO";

export const CONFIRMAR_COMPRA = "CONFIRMAR_COMPRA";
export const ACTUALIZAR_ESTADO_ENVIO = "ACTUALIZAR_ESTADO";

export const MAIL_ADMIN = "MAIL_ADMIN";

export const POST_REVIEW = "POST_REVIEW ";
export const GET_REVIEWS = "GET_REVIEWS";
export const GET_PRODUCT_REVIEWS = "GET_PRODUCT_REVIEWS";
export const GET_ALL_REVIEWS = "GET_ALL_REVIEWS";
export const DELETE_REVIEW = "DELETE_REVIEW";
export const CHANGE_MODAL_REVIEW = "CHANGE_MODAL_REVIEW";
export const CHANGE_MODAL_CLOSE = "CHANGE_MODAL_CLOSE";
export const CHANGE_MODAL_OPEN = "CHANGE_MODAL_OPEN";

export const DELETE_CART = "DELETE_CART";

export const GET_PEDIDOS_BEGIN = "GET_PEDIDOS_BEGIN";
export const GET_PEDIDOS_SUCCESS = "GET_PEDIDOS_SUCCESS";
export const GET_PEDIDOS_FAIL = "GET_PEDIDOS_SUCCESS";

export const GET_ALL_SUCURSALES = "GET_ALL_SUCURSALES";
